### ISSUE TITLE
New formatting of the "h_AATyped" column

### ISSUE THREAD

**Issue by kevin-wamae** [bailey-lab/SeekDeep#18]
Hi Nick, I noticed changes in the representation of the **h_AATyped** column.

I have been using the develop version of SeekDeep and I used to get this format from around a month ago:

- PF3D7_1343700.1--441P:446F:449G:453G:458N:467Q:469C - The alleles were indicated to the right of the codons

After updating to the latest version, it has since switched to this:

- PF3D7_1343700.1--P441:F446:G449:N458:**C469Y** - The alleles are now indicated to the left of the codons

I wondered what C469Y means. Is this a mixed infection where we see both C and Y alleles?

And Should I expect the following formats moving forward:

- PF3D7_1343700.1--P441:F446:G449:N458:**469Y** for a mutant at 469
- PF3D7_1343700.1--P441:F446:G449:N458:**C469** for a wildtype at 469
- PF3D7_1343700.1--P441:F446:G449:N458:**C469Y** for a mixed infection at 469

**Comment by nickjhathaway** [comment]
Several people asked to change the format to be more similar to how amino acid changes are reported in the literature (for example, for PfDHPS A581G), with the reference on the left side and reporting an allele on the right side only if it's different from the reference. The h_AATyped column is done per haplotype, so there won't be any mixes for h_AATyped column (a sample might have two different haplotypes with different h_AATyped column values which would be a mix infection). So, for now, the formatting of this column will be that there will always be an amino acid on the left of the position number, which will be the reference amino acid for this position, and there will only be an amino acid after this position if this haplotype is different from the reference. 

E.g. 

* PF3D7_1343700.1--P441:F446:G449:N458:***C469Y*** for mutant at 469, which the reference is C but for this haplotype, this position is Y 
* PF3D7_1343700.1--P441:F446:G449:N458:***C469*** for reference at 469 

If a sample has a mixed infection this won't be reflected in h_AATyped column but instead there will be two haplotypes with possibly different h_AATyped values (what makes it into the h_AATyped is supplied known mutation sites which have forced reporting and any thing that's variant above a certain threshold in the population, this frequency filter for what is considered variant is set at run time of processClusters step) 

For mixed infectious you would see something like this in the final results table: 

|s_Sample|h_popUID|h_AATyped|  
|---|---|---|  
|sample_1|tar1.00|PF3D7_1343700.1--P441:F446:G449:N458:***C469Y***|
|sample_1|tar1.01|PF3D7_1343700.1--P441:F446:G449:N458:***C469***|

This was being asked for because it wasn't always clear if the site was mutant or reference so the change was made to reflect the literature reporting and to make it clear when the position is a mutant.

**Comment by kevin-wamae** [comment]
Thanks @nickjhathaway:

- The new format makes it much clearer whether or not a mutation is present.
- It also improves data representation and will save me a few lines of code when determining the wild-type allele.
