### ISSUE TITLE
bibcpp compile error, gcc 4.9.3

### ISSUE THREAD

**Issue by DylanGraham** [bailey-lab/SeekDeep#2]
<pre>In file included from src/bibcpp/files.h:8:0,
                 from src/bibcpp.h:7,
                 from src/main.cpp:2:
./src/bibcpp/files/podVecIO.hpp: In function ‘std::vector<_RealType> bib::files::readPODvectorGz(boost::filesystem::path)’:
./src/bibcpp/files/podVecIO.hpp:55:31: error: there are no arguments to ‘gzbuffer’ that depend on a template parameter, so a declaration of ‘gzbuffer’ must be available [-fpermissive]
  gzbuffer(gzInFile, 128 * 1024);
                               ^
./src/bibcpp/files/podVecIO.hpp:55:31: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from src/bibcpp/files.h:9:0,
                 from src/bibcpp.h:7,
                 from src/main.cpp:2:
./src/bibcpp/files/gzTextFileCpp.hpp: In constructor ‘bib::files::gzTextFileCpp<BUFFER>::gzTextFileCpp(const string&, const string&)’:
./src/bibcpp/files/gzTextFileCpp.hpp:46:33: error: there are no arguments to ‘gzbuffer’ that depend on a template parameter, so a declaration of ‘gzbuffer’ must be available [-fpermissive]
   if (gzbuffer(file_, 128 * 1024)) {
                                 ^
make: *** [build/bibcppBuild/src/main.o] Error 1
</pre>

I had to add -fpermissive as suggested

**Comment by nickjhathaway** [comment]
That is likely caused by having an older version of libz which doesn't have gzbuffer(the one I use is normally version 1.2.8, I forget when gzbuffer was first incorporated into libz), so actually adding -fpermissive doesn't solve the problem it just makes the error message goes away and could cause undefined behavior if you go to read in a gz file.  So a better fix might be to either update to a newer libz or to call setup.py with the following 

`CXXFLAGS=-DNO_GZBUFFER_FUNC ./setup.py --compfile compfile.mk --outMakefile makefile-common.mk`

which will make compiling not use the gzbuffer function.  

Though if you don't read in gz files you won't have a problem without doing this.  

Nick

**Comment by DylanGraham** [comment]
Hi Nick, I've tried using the newer zlib with:

    CXXFLAGS=-I/usr/local/zlib/1.2.8/include ./setup.py --compfile compfile.mk --outMakefile makefile-common.mk
without success (same gzbuffer error).
Is SeekDeep using my environment variables, LD_LIBRARY_PATH and such?
It's being quite tough to install on Centos 6.7, I've tried gcc 4.9.3 and 6.2.0 so far.
Thanks

**Comment by nickjhathaway** [comment]
The LD_LIBRARY_PATH is used by the linker and will automatically always be used.  SeekDeep will use environmental variables LDFLAGS and CXXFLAGS.  I've seen this before where if there are two libz libraries installed the compiler will use the one it finds first and this is normally the system library.  I would honestly use 

`CXXFLAGS=-DNO_GZBUFFER_FUNC ./setup.py --compfile compfile.mk --outMakefile makefile-common.mk`
rather than trying to get the newer libz to be used as the gzbuffer setting doesn't add that much of a benefit and trying to get the compiler to search just the right paths can sometimes be challenging.  Also when running setup.py again, make sure to remove the "SeekDeep/external" to make sure the setup is using a clean install, this SeekDeep/external folder is when it installs all the dependencies.  

And if you really want to try to get the new libz to be used (again not really necessary) you can use `g++ -I/usr/local/zlib/1.2.8/include -v -x c++ /dev/null -fsyntax-only` to see what the include paths and their order are to see if the complier is finding the older library first 

Is this the only problem you're running into or are you having other troubles as well?  I've never tested on Centos before so I'm not sure what other problems you can run into. 

Nick

**Comment by DylanGraham** [comment]
For some reason hts fails with:
<pre>
hts:1.3.1 NOT found; building...
mkdir /usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/local/hts/1.3.1
mkdir /usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/build/hts/1.3.1
cloning from https://github.com/samtools/htslib.git
Cloning into '/usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/build/hts/1.3.1/hts'...
cd '/usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/build/hts/1.3.1/hts' && git checkout 1.3.1 && cd -
Note: checking out '1.3.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 0f298ce... Release 1.3.1: bug fix release, notably error checking
/usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/build/bibseq/v2.4.0/bibseq
cd '/usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/build/hts/1.3.1/hts' && CC=gcc CXX=g++ && autoheader && autoconf && ./configure --prefix='/usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/local/hts/1.3.1/hts' && make -j 20 && make install -j 20 && cd -
configure.ac:26: error: possibly undefined macro: m4_esyscmd_s
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
</pre>

Then I can manually run:
<pre>
cd '/usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/build/hts/1.3.1/hts' && CC=gcc CXX=g++ && autoheader && autoconf && ./configure --prefix='/usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/local/hts/1.3.1/hts' && make -j 20 && make install -j 20 && cd -
</pre>
to compile it successfully.

Now I used:
<pre>CXXFLAGS=-DNO_GZBUFFER_FUNC ./setup.py --compfile compfile.mk --outMakefile makefile-common.mk</pre>
as you suggested but I'm hitting more errors:
<pre>
mkdir -p build/bibcppBuild
mkdir -p bin
g++ -std=c++14 -Wall -ftemplate-depth=1024 -Werror=uninitialized -Werror=return-type -Wno-missing-braces -DNO_GZBUFFER_FUNC -O2 -funroll-loops -DNDEBUG   -march=native -mtune=native -I./src/ -isystem/usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/local/jsoncpp/1.7.1/jsoncpp/include -isystem/usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/local/boost/1_60_0/boost/include -isystem/usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/local/cppitertools/v0.1 -isystem/usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/local/pstreams/RELEASE_0_8_1 -fPIC -Dbibcpp_INSTALLDIR=\"/usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/local/bibcpp/v2.4.0/bibcpp\" -c src/main.cpp -o build/bibcppBuild/src/main.o
mkdir -p lib
In file included from src/bibcpp/files.h:8:0,
                 from src/bibcpp.h:7,
                 from src/main.cpp:2:
./src/bibcpp/files/podVecIO.hpp: In function ‘std::vector<_RealType> bib::files::readPODvectorGz(boost::filesystem::path)’:
./src/bibcpp/files/podVecIO.hpp:55:31: error: there are no arguments to ‘gzbuffer’ that depend on a template parameter, so a declaration of ‘gzbuffer’ must be available [-fpermissive]
  gzbuffer(gzInFile, 128 * 1024);
                               ^
./src/bibcpp/files/podVecIO.hpp:55:31: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
make: *** [build/bibcppBuild/src/main.o] Error 1
</pre>

**Comment by nickjhathaway** [comment]
Weird about hts, never seen that before.  And arg sorry about that, I added that other function right before the last release and forgot about the gzbuffer issue.  For me to get the compiler to use the correct zlib when compiling I normally do 

`LDFLAGS="-L/share/pkg/zlib/1.2.8/lib -Wl,-rpath,/share/pkg/zlib/1.2.8/lib" C_INCLUDE_PATH=/share/pkg/zlib/1.2.8/include:$C_INCLUDE_PATH CPLUS_INCLUDE_PATH=/share/pkg/zlib/1.2.8/include:$CPLUS_INCLUDE_PATH ./setup.py --compfile compfile.mk --outMakefile makefile-common.mk`

which for your setup looks like maybe this might work to be able to use the gzbuffer function.  

`LDFLAGS="-L/usr/local/zlib/1.2.8/lib -Wl,-rpath,/usr/local/zlib/1.2.8/lib" C_INCLUDE_PATH=/usr/local/zlib/1.2.8/include:$C_INCLUDE_PATH CPLUS_INCLUDE_PATH=/usr/local/zlib/1.2.8/include:$CPLUS_INCLUDE_PATH
 ./setup.py --compfile compfile.mk --outMakefile makefile-common.mk`

might work.  

Otherwise go to line /usr/local/src/SEEKDEEP/SeekDeep-2.4.0/external/build/bibcpp/v2.4.0/bibcpp/src/bibcpp/files/podVecIO.hpp :55 and either comment out or remove the line with gzbuffer on it, sorry about that.  

Nick

**Comment by DylanGraham** [comment]
Thanks Nick, it compiles now!

**Comment by nickjhathaway** [comment]
Yay! I'm curious was it the changing the file or setting the flags that worked? 

n

**Comment by DylanGraham** [comment]
The flags fixed it.
So apart from the `hts` strangeness it's a pretty smooth install.

**Comment by nickjhathaway** [comment]
Excellent, glad to hear
