### ISSUE TITLE
Dual barcode

### ISSUE THREAD

**Issue by Alishumali** [bailey-lab/SeekDeep#6]
Hi, 
I'm new to bioinformatics and have come across your tool recently. Thank you for putting such a versatile tool together. 
At the moment I work a lot with dual barcoded primers. For that, I was wondering if demultiplexing can be done using both barcodes combination in SeekDeep. What I mean here is that our fwd primer will have a barcode sequence and our rev primer will have a barcode sequence and together they are unique, but not alone. Also sometimes the rev barcode-primer might be in reverse complement (which you already have a flag for). As a final request can my question also apply to both single & paired-end reads. 

I appreciate any help.

Ali

**Comment by JeffAndBailey** [comment]
The short answer is yes.   You can  specify demultiplexing on specific 
combinations of forward and reverse barcodes on single or paired ends.   
We have seen at this point almost every possible barcoding scheme -- 
although we continued to be surprised.

For paired end instead of extractor, you will want to use 
extractorPairedEnd

http://baileylab.umassmed.edu/SeekDeep/extractor_usage.html

If you are going to use SeekDeep for downstream analysis beyond the  
demultiplexing extraction. Here is a tutorial  (after demultiplexing) of 
analyzing paired end reads.

http://baileylab.umassmed.edu/SeekDeep/tutorial_PairedEnd_noMIDs.html

Hope that helps. Nick may have more to add.

Best, Jeff

**Comment by Alishumali** [comment]
Thank you Jeff, 

I see that i can demultiplex using a single barcode approach and multiple primers but i was hoping that SeekDeep will take two sets of barcodes attached to each read in this way **P7adapter-barcode1-F-primer and P5adapter-barcode2-R-primer** (the combination is unique not each barcode separatley). So if it is possible at all, the barcode mapping file will be something like this:  
**target - fwd_primer - rev_primer
id - barcode1 - barcode2**

I imagine you can add a combinatorial barcode function to the multiplex option you already have.

_To answer you usage question, Yes, i have already run SeekDeep on some demultiplexed fastq files and i'm happy with the outcome. I just didn't know how to use a closed reference approach for taxonomy assignment of 16s rRNA V4-reads._

Thank you again,
Ali

**Comment by nickjhathaway** [comment]
Hi Ali,
Sorry for the delay, I am currently finishing up Medical School and haven't been able to get around to answering messages. So you can, in fact, do exactly as you suggested and have a second barcode column with the barcode that is associated with the reverse primer, I had the option in the develop branch and just updated the code so the released version has this feature, let me know if you have any trouble with using it. 

The barcode/primer file would look like you suggested
**target - fwd_primer - rev_primer**
**id - barcode1 - barcode2**

Best,
Nick

**Comment by Alishumali** [comment]
Hi Nick,

Thank you for getting back to me. Congrats on finishing your medical studies. 

Thank you for updating the code. I will give it a try and report on how i go.

Cheers,
Ali
